export default {
  BLACK: '#000000',
  MOOD_HAPPY: '#FFFAE4',
  MOOD_NEUTRAL: '#E8FEFF',
  MOOD_SAD: '#E9EFFF',
  MOOD_STRESSED: '#FFE0E0',
  TEXT_HAPPY: '#FFCF30',
  TEXT_NEUTRAL: '#7DE4EA',
  TEXT_SAD: '#4370F2',
  TEXT_STRESSED: '#FF2727',
  WHITE: '#FFFFFF',
};
